name: Send notification
on:
  workflow_run:
    workflows: ["CI/CD workflow"]
    types:
      - completed
jobs:
  send_email: 
    name: Send email
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CI/CD job status - ${{ github.event.workflow_run.conclusion }}
  #        html_body: file://email/template
          html_body: |
            <p>Executed by: ${{ github.actor}}</p>
            <p>Job name: ${{ github.job }}</p>
            <p>Repository: ${{ github.repository }}</p>
            <p>Status:${{ job.status }}</p>
          to: aws1sofiiamyk@gmail.com 
          from: Sofiia Myk
