name: CI/CD workflow
on:
  push:
    paths-ignore:
      - '.github/workflows/CI.yaml'
      - '.gitignore'
jobs:
  email:
    name: Test email
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Hello World
      run: echo Hello, world!
    - name: Send email
      uses: dawidd6/action-send-mail@v3.7.1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: aws1sofiiamyk@gmail.com 
        from: Sofiia Myk
